OnlineStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from myapp.views import index_page, RegisterView, ConfirmLogoutView
from myapp.forms import LoginForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_page, name='index'),
    path('store/', include('myapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_page, name='index_page'),

    # Booking
    path('booking/create/', views.BookingCreateView.as_view(), name='booking_create'),
    path('booking/detail/', views.BookingDetailView.as_view(), name='booking_detail'),
    path('booking/delete/', views.BookingDeleteView.as_view(), name='booking_delete'),
    path('booking/update/', views.BookingUpdateQuantityView.as_view(), name='booking_update_quantity'),
    path('booking/clear/', views.BookingClearView.as_view(), name='booking_clear'),

    # User
    path('profile/', views.UserDetailView.as_view(), name='profile_user'),
    path('user/profile/update/', views.UserUpdateView.as_view(), name='profile_update'),
    path('user/password/update/', views.UserPasswordUpdateView.as_view(), name='password_update'),
    path('user/comments/', views.UserCommentsListView.as_view(), name='user_comments'),
    path('user/favorites/', views.UserFavoritesListView.as_view(), name='user_favorites'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/confirm/', views.ConfirmLogoutView.as_view(), name='confirm_logout'),

    # Category
    path('category/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/update/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),
    path('category/all', views.CategoryListView.as_view(), name='category_list'),

    # Product
    path('product/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/favorite/', views.ProductFavoriteView.as_view(), name='favorite_product'),
    path('search/', views.ProductSearchView.as_view(), name='product_search'),

    # Comment
    path('product/<int:pk>/comment/create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('product/<int:pk>/comments/', views.CommentListView.as_view(), name='comment_list'),

    # Order
    path('order/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('order/confirm/<int:order_id>/', views.OrderConfirmView.as_view(), name='order_confirm'),
    path('order/list/', views.OrderListView.as_view(), name='order_list'),
    path('order/notifications/', views.OrderNotificationView.as_view(), name='order_notification'),

]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.validators import RegexValidator



# --- Категорія товара
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# --- Товар
class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='myapp/images/', blank=True, default='myapp/images/no-image.jpg')
    is_active = models.BooleanField(default=True)
    favorites = models.ManyToManyField(User, related_name='favorite_product', blank=True)

    def __str__(self):
        return self.name


# --- Відгук
class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', null=True)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

    class Meta:
        unique_together = ('product', 'user')

    def __str__(self):
        return f'Відгук {self.user.username} до "{self.product.name}"'


# --- Кошик
class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bookings')

    def __str__(self):
        return f'Кошик {self.user.username}'

    def get_total_price(self):
        return sum(item.product.price * item.quantity for item in self.items.all() if item.product)


# --- Товар у кошику
class BookingItem(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} × {self.product.name}'


# --- Замовлення
class Order(models.Model):
    DELIVERY_CHOICES = [
        ('nova_poshta_branch', 'Самовивіз з Нової Пошти'),
        ('nova_poshta_postomat', 'Самовивіз з поштоматів Нової Пошти'),
        ('meest_branch', 'Самовивіз з Meest ПОШТА'),
        ('ukrposhta_branch', 'Самовивіз з УКРПОШТИ'),
        ('meest_courier', 'Курʼєр Meest ПОШТА'),
        ('nova_poshta_courier', 'Курʼєр Нової Пошти'),
    ]

    PAYMENT_CHOICES = [
        ('card', 'Оплата картою Visa/MasterCard'),
        ('cash_on_delivery', 'Оплата під час отримання товару'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    # доставка та оплата
    delivery_method = models.CharField(max_length=30, choices=DELIVERY_CHOICES, default='nova_poshta_branch')
    delivery_address = models.CharField(max_length=255, default='Потребує уточнення')
    payment_method = models.CharField(max_length=30, choices=PAYMENT_CHOICES, default='cash_on_delivery')

    def __str__(self):
        return f"Замовлення № {self.id} від {self.user.username}"

    def clean(self):
        restricted_delivery = [
            'nova_poshta_postomat',
        ]
        if self.delivery_method in restricted_delivery and self.payment_method == 'cash_on_delivery':
            raise ValidationError("Цей спосіб доставки не підтримує оплату під час отримання товару")


# --- Товар в замовленні
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)


# --- Профіль моделі User
# --- мобільний телефон
phone_validator = RegexValidator(
    regex=r'^\+380\d{9}$',
    message="Номер телефону має бути у форматі +380XXXXXXXXX"
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(
        max_length=13,
        blank=True,
        validators=[phone_validator]
    )

    def __str__(self):
        return f"Профіль {self.user.username}"


# --- Сигнал Менеджеру про нове Замовлення
class OrderNotification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_notifications')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_notifications')
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"Сповіщення для {self.user.username} про замовлення № {self.order.id}"

    def mark_as_read(self):
        self.is_read = True
        self.save()

myapp/forms.py
from django import forms
from myapp.models import Category, Product, Comment, UserProfile
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator



class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
                    'name': 'Назва категорії',
                }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'description', 'price', 'image']
        labels = {
                    'name': 'Назва товару',
                    'category': 'Категорія',
                    'description': 'Опис',
                    'price': 'Ціна',
                    'image': 'Зображення',
                }



# --- RegistrationForm
class MyUserRegistrationForm(UserCreationForm):
    username = forms.CharField(
        label='Логін',
        help_text='Логін має бути унікальним. Не більше 150 символів. Тільки літери, цифри та символи @/./+/-/_',
    )
    password1 = forms.CharField(
        label='Пароль',
        help_text='Пароль має містити щонайменше 8 символів, мінімум одну літеру та одну цифру.',
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label='Підтвердження пароля',
        help_text='Повторіть той самий пароль для підтвердження.',
        widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


# --- LoginForm
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Логін")
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)

# --- UpdateUserForm
phone_validator = RegexValidator(
    regex=r'^\+380\d{9}$',
    message="Номер телефону має бути у форматі +380XXXXXXXXX"
)

class UserUpdateForm(forms.ModelForm):
    phone = forms.CharField(
        max_length=13,
        required=False,
        label='Телефон',
        validators=[phone_validator]
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        labels = {
            'first_name': 'Ім`я',
            'last_name': 'Прізвище',
            'email': 'Ел.пошта',
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.get('instance')
        super().__init__(*args, **kwargs)
        if user and hasattr(user, 'userprofile'):
            self.fields['phone'].initial = user.userprofile.phone

    def save(self, commit=True):
        user = super().save(commit)
        phone = self.cleaned_data.get('phone')
        profile, created = UserProfile.objects.get_or_create(user=user)
        profile.phone = phone
        if commit:
            profile.save()
        return user


# --- UpdateUserPassword
class UserPasswordUpdateForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Новий пароль',
        widget=forms.PasswordInput(),
        help_text='Пароль має містити щонайменше 8 символів, мінімум одну літеру та одну цифру.'
    )
    password2 = forms.CharField(
        label='Підтвердження пароля',
        widget=forms.PasswordInput(),
        help_text='Повторіть той самий пароль для підтвердження.'
    )

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        labels = {
            'username': 'Логін',
        }

    def clean(self):
        cleaned_data = super().clean()
        p1 = cleaned_data.get('password1')
        p2 = cleaned_data.get('password2')
        if p1 and p2 and p1 != p2:
            raise ValidationError("Паролі не співпадають.")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get('password1')
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user



# --- CommentForm
RATING_CHOICES = [
    (5, '⭐⭐⭐⭐⭐ 5 - чудово'),
    (4, '⭐⭐⭐⭐ 4 - добре'),
    (3, '⭐⭐⭐ 3 - нормально'),
    (2, '⭐⭐ 2 - так собі'),
    (1, '⭐ 1 - погано'),
]

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'rating']
        labels = {
            'text': 'Текст відгуку',
            'rating': 'Оцінка (найвищий бал 5)',
        }
        widgets = {
            'rating': forms.Select(choices=RATING_CHOICES)
        }

myapp/templates/myapp/order/order_confirm.html
{% extends 'myapp/template.html' %}
{% load static %}

{% block content %}
    <div class="page-container text-center">
        <div class="content-box">
            {% if show_success_message %}
                <h2 class="main-heading">Ваше замовлення було успішно оформлено!</h2>
            {% endif %}
            <h5>Номер замовлення: <strong class="info-label">{{ order.id }}</strong></h5>
            <p>Дата: {{ order.date|date:"d.m.Y H:i" }}</p>
            <p>Сума: <strong class="info-label">{{ order.total_price }} грн</strong></p>
            {% if show_success_message %}
                <h5>Дякуємо за замовлення!</h5>
            {% endif %}

        </div>

        <div class="content-box">
            <p> Спосіб доставки: {{ order.get_delivery_method_display }}</p>
            <p> Адреса доставки: {{ order.delivery_address }}</p>
            <p> Спосіб оплати: {{ order.get_payment_method_display }}</p>
        </div>


    <div class="content-box">
        {% for item in order_items %}
        <div class="comment-card">
            <div class="comment-header">
                <div class="d-flex text-left">
                    <div style="width: 80px; margin-right: 15px;">
                        <a href="{% url 'product_detail' item.product.id %}">
                            {% if item.product and item.product.image %}
                                <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" style="width: 100%; height: auto; border-radius: 8px;">
                            {% else %}
                                <div class="text-muted small">Немає фото</div>
                            {% endif %}
                        </a>
                    </div>
                    <div>
                        <a href="{% url 'product_detail' item.product.id %}">
                            <span class="product-name">{{ item.product.name }}</span>
                        </a>
                        <div class="comment-date">{{ item.price|floatformat:2 }} грн x {{ item.quantity }} од.</div>
                    </div>
                </div>
            </div>

            <div class="comment-text text-end">
                <strong>{{ item.total|floatformat:2 }} грн</strong>
            </div>
        </div>
        {% endfor %}
    </div>


        {% if came_from_order_notification %}
            <a href="{% url 'order_notification' %}" class="universal-btn back-btn mt-3">
                <i class="fas fa-arrow-left"></i> Назад до повідомлень
            </a>
        {% else %}
            <a href="{% url 'order_list' %}" class="universal-btn back-btn mt-3">
                <i class="fas fa-list"></i> Переглянути всі замовлення
            </a>
        {% endif %}
    </div>
{% endblock %}

myapp/templates/myapp/order/order_create.html
{% extends 'myapp/template.html' %}
{% load static %}

{% block content %}
    <div class="page-container">
        <div class="content-box">
            <h2 class="main-heading">Оформлення замовлення</h2>

            <div class="form-group">
                <h5 class="sub-heading">Ваші контактні дані:</h5>
                <ul class="info-list">
                    <li><strong class="info-label">Ім’я:</strong> {{ request.user.first_name|default:"[Обов’язково заповнити]" }}</li>
                    <li><strong class="info-label">Прізвище:</strong> {{ request.user.last_name|default:"[Обов’язково заповнити]" }}</li>
                    <li><strong class="info-label">Телефон:</strong> {{ request.user.userprofile.phone|default:"[Обов’язково заповнити]" }}</li>
                </ul>
                {% if not request.user.first_name or not request.user.last_name or not request.user.userprofile.phone %}
                    <a href="{% url 'profile_update' %}" class="universal-btn orange-outline-btn cusl1">Редагувати профіль</a>
                {% endif %}
            </div>

            <div class="product-list-container">
                {% for item in items %}
                <div class="order-item card-date">
                    <div class="card-item">
                        <strong>{{ item.name }}</strong><br>
                        <small>{{ item.quantity }} x {{ item.price }} грн</small>
                    </div>
                    <div class="price-r">{{ item.total }} грн</div>
                </div>
                {% endfor %}
            </div><br>

            <div class="text-center">
                <h4 class="cart-total-price">Загальна сума: {{ total_price }} грн</h4>
            </div>
        </div>

        <div class="content-box">
            {% if error_message %}
            <strong class="error-message-login">{{ error_message }}</strong>
            {% endif %}
            <form method="get" action="{% url 'order_create' %}" class="form-group">
                <input type="hidden" name="delivery_method" value="{{ selected_delivery_method }}">
                <input type="hidden" name="delivery_address" value="{{ delivery_address }}">
                <div class="form-group">
                    <label for="payment_method">Спосіб оплати:</label>
                    <select name="payment_method" id="payment_method" onchange="this.form.submit()">
                        {% for value, label in payment_choices %}
                            <option value="{{ value }}" {% if value == selected_payment_method %}selected{% endif %}>{{ label }}</option>
                        {% endfor %}
                    </select>
                </div>
            </form>

            <form method="post" action="{% url 'order_create' %}" id="order-form">
                {% csrf_token %}
                <input type="hidden" name="action_type" value="submit_order">
                <input type="hidden" name="payment_method" value="{{ selected_payment_method }}">

                <div class="form-group">
                    <label for="delivery_method">Спосіб доставки:</label>
                    <select name="delivery_method" id="delivery_method" required>
                        {% for value, label in delivery_choices %}
                            <option value="{{ value }}" {% if value == selected_delivery_method %}selected{% endif %}>{{ label }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="delivery_address">Адреса доставки:</label>
                    <input type="text" name="delivery_address" id="delivery_address" value="{{ delivery_address }}" required>
                </div>

                {% if selected_payment_method == 'card' %}
                    <div class="form-container">
                        <h5 class="sub-heading">Дані картки</h5>
                        <div class="form-group">
                            <label for="card_number">Номер карти:</label>
                            <input type="text" name="card_number" id="card_number" maxlength="16" pattern="\d{16}" required>
                        </div>
                        <div class="button-group one-line-buttons">
                            <div class="form-group">
                                <label>Термін дії:</label>
                                <div class="one-line-form card-date cusl5">
                                    <div>
                                        <input type="text" name="card_month" id="card_month" maxlength="2" pattern="\d{2}" required>
                                    </div>
                                    <div style="font-size: 20px;">/</div>
                                    <div>
                                        <input type="text" name="card_year" id="card_year" maxlength="2" pattern="\d{2}" required>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="card_cvv">CVV:</label>
                                <input type="password" name="card_cvv" id="card_cvv" maxlength="3" pattern="\d{3}" required>
                            </div>
                        </div>
                    </div>

                {% endif %}

                <div class="one-line-buttons">
                    {% if request.user.first_name and request.user.last_name and request.user.userprofile.phone %}
                        <button type="submit" class="universal-btn orange-filled-btn cusl2">
                            <i class="fas fa-check"></i> Підтвердити замовлення
                        </button>
                    {% endif %}
                    <a href="{% url 'booking_detail' %}" class="universal-btn back-btn cusl2">
                        <i class="fas fa-edit"></i> Змінити замовлення
                    </a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/order/order_list.html
{% extends 'myapp/template.html' %}

{% block content %}
    <div class="comment-container">
        <h2 class="main-heading">Ваші замовлення</h2>

        {% if orders %}
        <div class="comment-grid">
            {% for order in orders %}
            <a href="{% url 'order_confirm' order.id %}" class="comment-card list-group-item custom-hover">
                <div class="comment-header" style="height: 10px;">
                    <strong>Замовлення № {{ order.id }}</strong><br>
                    <div class="d-flex align-items-center gap-2 flex-wrap">
                        {% for item in order.items.all %}
                            {% if item.product and item.product.image %}
                                <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" height="40" class="rounded border">
                            {% endif %}
                        {% endfor %}
                    </div>
                    <small>{{ order.total_price }} грн</small>
                </div>
                <span class="comment-rating" style="color: #28a745;">{{ order.date|date:"d.m.Y H:i" }}</span>
            </a>
            {% endfor %}
        </div>
        {% else %}
        <p>У вас ще немає замовлень.</p>
        {% endif %}
        <div class="comment-actions-bottom footer-class">
            <a class="universal-btn back-btn" href="javascript:history.back()">Назад</a>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/order/order_notification.html
{% extends 'myapp/template.html' %}

{% block title %} Повідомлення про замовлення {% endblock %}

{% block content %}
    <div class="comment-container">
        <h2 class="main-heading">Повідомлення про замовлення</h2>

        {% if notifications_all %}
            <div class="d-flex gap-2 flex-wrap mb-3">
                <a href="?filter=unread" class="universal-btn orders-btn {% if filter_value == 'unread' %}active{% endif %}">Не перевірені: {{ unread_count }}</a>
                <a href="?filter=read" class="universal-btn orders-btn {% if filter_value == 'read' %}active{% endif %}">Перевірені: {{ read_count }}</a>
                <a href="?filter=all" class="universal-btn orders-btn {% if filter_value == 'all' %}active{% endif %}">Всі: {{ total_count }}</a>
            </div>



            <div class="comment-grid">
                {% for notification in notifications %}
                    <div class="comment-card list-group-item custom-hover {% if not notification.is_read %}border border-warning{% endif %}">
                        <div class="comment-header">
                            <strong>
                                <a href="{% url 'order_confirm' order_id=notification.order.id %}?from_notification=1">
                                    Замовлення №{{ notification.order.id }}
                                </a>
                            </strong>
                            <br>
                            <small>{{ notification.created_at|date:"d.m.Y, H:i" }}</small>
                        </div>
                        <div class="comment-body">
                            <p>{{ notification.message }}</p>
                        </div>

                        <div class="comment-actions-bottom d-flex gap-2 flex-wrap">
                            {% if not notification.is_read %}
                                <form method="post" class="mark-read-form">
                                    {% csrf_token %}
                                    <input type="hidden" name="notification_id" value="{{ notification.pk }}">
                                    <button type="submit" class="universal-btn orders-btn">Перевити</button>
                                </form>
                            {% else %}

                               <span class="read-label text-success" ><h4>✅ Перевірено</h4></span>
                            {% endif %}
                        </div>
                  </div>
              {% endfor %}
            </div>
        {% else %}
          <p>Наразі немає сповіщень.</p>
        {% endif %}

        <div class="comment-actions-bottom footer-class">
          <a class="universal-btn back-btn" href="{% url 'profile_user' %}">Назад</a>
        </div>
    </div>
{% endblock %}