OnlineStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from myapp.views import index_page, RegisterView, ConfirmLogoutView
from myapp.forms import LoginForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_page, name='index'),
    path('store/', include('myapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_page, name='index_page'),

    # Booking
    path('booking/create/', views.BookingCreateView.as_view(), name='booking_create'),
    path('booking/detail/', views.BookingDetailView.as_view(), name='booking_detail'),
    path('booking/delete/', views.BookingDeleteView.as_view(), name='booking_delete'),
    path('booking/update/', views.BookingUpdateQuantityView.as_view(), name='booking_update_quantity'),
    path('booking/clear/', views.BookingClearView.as_view(), name='booking_clear'),

    # User
    path('profile/', views.UserDetailView.as_view(), name='profile_user'),
    path('user/profile/update/', views.UserUpdateView.as_view(), name='profile_update'),
    path('user/password/update/', views.UserPasswordUpdateView.as_view(), name='password_update'),
    path('user/comments/', views.UserCommentsListView.as_view(), name='user_comments'),
    path('user/favorites/', views.UserFavoritesListView.as_view(), name='user_favorites'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/confirm/', views.ConfirmLogoutView.as_view(), name='confirm_logout'),

    # Category
    path('category/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/update/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),
    path('category/all', views.CategoryListView.as_view(), name='category_list'),

    # Product
    path('product/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/favorite/', views.ProductFavoriteView.as_view(), name='favorite_product'),
    path('search/', views.ProductSearchView.as_view(), name='product_search'),

    # Comment
    path('product/<int:pk>/comment/create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('product/<int:pk>/comments/', views.CommentListView.as_view(), name='comment_list'),

    # Order
    path('order/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('order/confirm/<int:order_id>/', views.OrderConfirmView.as_view(), name='order_confirm'),
    path('order/list/', views.OrderListView.as_view(), name='order_list'),
    path('order/notifications/', views.OrderNotificationView.as_view(), name='order_notification'),

]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.validators import RegexValidator



# --- Категорія товара
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# --- Товар
class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='myapp/images/', blank=True, default='myapp/images/no-image.jpg')
    is_active = models.BooleanField(default=True)
    favorites = models.ManyToManyField(User, related_name='favorite_product', blank=True)

    def __str__(self):
        return self.name


# --- Відгук
class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', null=True)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

    class Meta:
        unique_together = ('product', 'user')

    def __str__(self):
        return f'Відгук {self.user.username} до "{self.product.name}"'


# --- Кошик
class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bookings')

    def __str__(self):
        return f'Кошик {self.user.username}'

    def get_total_price(self):
        return sum(item.product.price * item.quantity for item in self.items.all() if item.product)


# --- Товар у кошику
class BookingItem(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} × {self.product.name}'


# --- Замовлення
class Order(models.Model):
    DELIVERY_CHOICES = [
        ('nova_poshta_branch', 'Самовивіз з Нової Пошти'),
        ('nova_poshta_postomat', 'Самовивіз з поштоматів Нової Пошти'),
        ('meest_branch', 'Самовивіз з Meest ПОШТА'),
        ('ukrposhta_branch', 'Самовивіз з УКРПОШТИ'),
        ('meest_courier', 'Курʼєр Meest ПОШТА'),
        ('nova_poshta_courier', 'Курʼєр Нової Пошти'),
    ]

    PAYMENT_CHOICES = [
        ('card', 'Оплата картою Visa/MasterCard'),
        ('cash_on_delivery', 'Оплата під час отримання товару'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    # доставка та оплата
    delivery_method = models.CharField(max_length=30, choices=DELIVERY_CHOICES, default='nova_poshta_branch')
    delivery_address = models.CharField(max_length=255, default='Потребує уточнення')
    payment_method = models.CharField(max_length=30, choices=PAYMENT_CHOICES, default='cash_on_delivery')

    def __str__(self):
        return f"Замовлення № {self.id} від {self.user.username}"

    def clean(self):
        restricted_delivery = [
            'nova_poshta_postomat',
        ]
        if self.delivery_method in restricted_delivery and self.payment_method == 'cash_on_delivery':
            raise ValidationError("Цей спосіб доставки не підтримує оплату під час отримання товару")


# --- Товар в замовленні
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)


# --- Профіль моделі User
# --- мобільний телефон
phone_validator = RegexValidator(
    regex=r'^\+380\d{9}$',
    message="Номер телефону має бути у форматі +380XXXXXXXXX"
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(
        max_length=13,
        blank=True,
        validators=[phone_validator]
    )

    def __str__(self):
        return f"Профіль {self.user.username}"


# --- Сигнал Менеджеру про нове Замовлення
class OrderNotification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_notifications')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_notifications')
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"Сповіщення для {self.user.username} про замовлення № {self.order.id}"

    def mark_as_read(self):
        self.is_read = True
        self.save()

myapp/forms.py
from django import forms
from myapp.models import Category, Product, Comment, UserProfile
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator



class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
                    'name': 'Назва категорії',
                }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'description', 'price', 'image']
        labels = {
                    'name': 'Назва товару',
                    'category': 'Категорія',
                    'description': 'Опис',
                    'price': 'Ціна',
                    'image': 'Зображення',
                }



# --- RegistrationForm
class MyUserRegistrationForm(UserCreationForm):
    username = forms.CharField(
        label='Логін',
        help_text='Логін має бути унікальним. Не більше 150 символів. Тільки літери, цифри та символи @/./+/-/_',
    )
    password1 = forms.CharField(
        label='Пароль',
        help_text='Пароль має містити щонайменше 8 символів, мінімум одну літеру та одну цифру.',
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label='Підтвердження пароля',
        help_text='Повторіть той самий пароль для підтвердження.',
        widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


# --- LoginForm
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Логін")
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)

# --- UpdateUserForm
phone_validator = RegexValidator(
    regex=r'^\+380\d{9}$',
    message="Номер телефону має бути у форматі +380XXXXXXXXX"
)

class UserUpdateForm(forms.ModelForm):
    phone = forms.CharField(
        max_length=13,
        required=False,
        label='Телефон',
        validators=[phone_validator]
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        labels = {
            'first_name': 'Ім`я',
            'last_name': 'Прізвище',
            'email': 'Ел.пошта',
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.get('instance')
        super().__init__(*args, **kwargs)
        if user and hasattr(user, 'userprofile'):
            self.fields['phone'].initial = user.userprofile.phone

    def save(self, commit=True):
        user = super().save(commit)
        phone = self.cleaned_data.get('phone')
        profile, created = UserProfile.objects.get_or_create(user=user)
        profile.phone = phone
        if commit:
            profile.save()
        return user


# --- UpdateUserPassword
class UserPasswordUpdateForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Новий пароль',
        widget=forms.PasswordInput(),
        help_text='Пароль має містити щонайменше 8 символів, мінімум одну літеру та одну цифру.'
    )
    password2 = forms.CharField(
        label='Підтвердження пароля',
        widget=forms.PasswordInput(),
        help_text='Повторіть той самий пароль для підтвердження.'
    )

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        labels = {
            'username': 'Логін',
        }

    def clean(self):
        cleaned_data = super().clean()
        p1 = cleaned_data.get('password1')
        p2 = cleaned_data.get('password2')
        if p1 and p2 and p1 != p2:
            raise ValidationError("Паролі не співпадають.")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get('password1')
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user



# --- CommentForm
RATING_CHOICES = [
    (5, '⭐⭐⭐⭐⭐ 5 - чудово'),
    (4, '⭐⭐⭐⭐ 4 - добре'),
    (3, '⭐⭐⭐ 3 - нормально'),
    (2, '⭐⭐ 2 - так собі'),
    (1, '⭐ 1 - погано'),
]

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'rating']
        labels = {
            'text': 'Текст відгуку',
            'rating': 'Оцінка (найвищий бал 5)',
        }
        widgets = {
            'rating': forms.Select(choices=RATING_CHOICES)
        }

myapp/templates/myapp/user/confirm_logout.html
{% extends 'myapp/template.html' %}
{% load static %}

{% block title %} Підтвердження виходу {% endblock %}

{% block content %}
    <div class="page-container">
        <div class="content-box text-center">
            <h2 class="sub-heading">
                {% if user.first_name %}
                    {{ user.first_name }} {{ user.last_name }}
                {% else %}
                    {{ user.username }}
                {% endif %}
            </h2>
            <h2 class="sub-heading">Ви справді хочете вийти з власного профілю користувача?</h2>
            <form method="post">
                {% csrf_token %}
                <div class="button-group one-line-buttons">
                    <button type="submit" class="universal-btn orange-filled-btn">
                        Вийти
                    </button>
                    <a href="javascript:history.back()" class="universal-btn back-btn">
                        Назад
                    </a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/user/password_update.html
{% extends 'myapp/template.html' %}
{% load static %}

{% block title %} Зміна логіну та пароля {% endblock %}

{% block content %}
    <div class="page-container">
        <div class="content-box">
            <form method="post">
                <h2 class="sub-heading text-center">Змінити логін або пароль</h2>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control" {% if field.value %}value="{{ field.value }}"{% endif %}>
                        {% if field.errors %}
                            <div class="error-text">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="button-group one-line-buttons">
                    <button type="submit" class="universal-btn orange-filled-btn">Зберегти</button>
                    <a href="javascript:history.back()" class="universal-btn back-btn cusl">Назад</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/user/profile.html
{% extends 'myapp/template.html' %}
{% load static %}

{% block title %} Профіль користувача {% endblock %}

{% block content %}
    <div class="page-container">
        <div class="content-box h">
            {% if user.groups.all|length > 0 %}
                {% for group in user.groups.all %}
                    {% if group.name == "Manager" %}
                        <h1 class="main-heading">Профіль менеджера</h1>
                    {% else %}
                        <h1 class="main-heading">Профіль користувача</h1>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <ul class="info-list">
                <li><span class="info-label">Логін:</span> {{ profile_user.username }}</li>
                <li><span class="info-label">Ім’я:</span> {{ profile_user.first_name }}</li>
                <li><span class="info-label">Прізвище:</span> {{ profile_user.last_name }}</li>
                <li><span class="info-label">Телефон:</span> {{ profile_user.userprofile.phone }}</li>
                <li><span class="info-label">Email:</span> {{ profile_user.email }}</li>
                {% if user.groups.all|length > 0 %}
                    {% for group in user.groups.all %}
                        {% if group.name == "Manager" %}
                            <li><span class="info-label">Група:</span> {% for group in profile_user.groups.all %}{{ group.name }} {% endfor %}</li>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <li><span class="info-label">Дата реєстрації:</span> {{ profile_user.date_joined|date:"d.m.Y, H:i" }}</li>
            </ul>


            {% if user.groups.all|length > 0 %}
                {% for group in user.groups.all %}
                    {% if group.name == "Client" %}
                        <div class="card-container more-info">
                            <a href="{% url 'user_comments' %}" class="universal-btn review-btn">
                                <i class="fas fa-comment-dots"></i> Відгуки
                            </a>
                            <a href="{% url 'user_favorites' %}" class="universal-btn wishlist-btn">
                                <i class="fas fa-heart"></i> Список бажань
                            </a>
                            <a href="{% url 'order_list' %}" class="universal-btn orders-btn">
                                <i class="fas fa-box-open"></i> Замовлення
                            </a>
                        </div>
                    {% elif group.name == "Manager" %}
                        <div class="card-container more-info">
                            <a href="{% url 'product_create' %}" class="universal-btn review-btn">
                                <i class="fas fa-plus"></i> Додати товар
                            </a>
                            <a href="{% url 'category_create' %}" class="universal-btn wishlist-btn">
                                <i class="fas fa-plus"></i> Додати категорію
                            </a>
                            <a href="{% url 'category_list' %}" class="universal-btn orders-btn">
                                <i class="fas fa-list"></i> Список категорій
                            </a>
                            <a href="{% url 'order_notification' %}" class="universal-btn orders-btn">
                                <i class="fas fa-box-open"></i> Перевірка Замовлень
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}

<!--             <div class="card-container more-info">-->
<!--                <a href="{% url 'user_comments' %}" class="universal-btn review-btn">-->
<!--                    <i class="fas fa-comment-dots"></i> Відгуки-->
<!--                </a>-->
<!--                <a href="{% url 'user_favorites' %}" class="universal-btn wishlist-btn">-->
<!--                    <i class="fas fa-heart"></i> Список бажань-->
<!--                </a>-->
<!--                <a href="{% url 'order_list' %}" class="universal-btn orders-btn">-->
<!--                    <i class="fas fa-box-open"></i> Замовлення-->
<!--                </a>-->
<!--            </div>-->


            <div class="button-group">
                <a href="{% url 'index' %}" class="universal-btn back-btn">
                    На головну
                </a>
                {% if request.user.id == profile_user.id %}
                    <a href="{% url 'profile_update' %}" class="universal-btn orange-outline-btn">
                        Редагувати профіль
                    </a>
                    <a href="{% url 'password_update' %}" class="universal-btn orange-outline-btn">
                        Редагувати логін/пароль
                    </a>
                {% endif %}

                {% if user.is_authenticated %}
                    <a href="{% url 'confirm_logout' %}" class="universal-btn orange-filled-btn">
                        Вийти з аккаунту
                    </a>
                {% endif %}
            </div>
        </div>

    </div>
{% endblock %}

myapp/templates/myapp/user/profile_update.html
{% extends 'myapp/template.html' %}
{% load static %}

{% block title %} Редагування профілю {% endblock %}

{% block content %}
    <div class="page-container">
        <div class="content-box">
            <form method="post">
                <h2 class="sub-heading text-center">Редагувати профіль користувача</h2>
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group">
                    {{ field.label_tag }}
                    <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control" {% if field.value %}value="{{ field.value }}"{% endif %}>
                    {% if field.errors %}
                      <div class="error-text">{{ field.errors }}</div>
                    {% endif %}
                  </div>
                {% endfor %}
                <div class="button-group one-line-buttons">
                  <button type="submit" class="universal-btn orange-filled-btn">Зберегти</button>
                  <a href="javascript:history.back()" class="universal-btn back-btn cusl">Назад</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/user/user_comments.html
{% extends 'myapp/template.html' %}

{% block title %} Відгуки користувача {% endblock %}

{% block content %}
    <div class="comment-container">
        <h2>Всі відгуки {{ profile_user.username }}</h2>

        {% if comments %}
            <div class="comment-grid">
                {% for comment in comments %}
                    <div class="comment-card">
                        <div class="comment-header">
                            <a href="{% url 'product_detail' comment.product.id %}">
                                <strong>{{ comment.product.name }}</strong>
                            </a>
                            <span class="comment-date">{{ comment.date|date:"d.m.Y, H:i" }}</span>
                        </div>

                        <div class="comment-rating">
                            <em>Оцінка: {{ comment.rating }}</em>
                            <span>
                                {% for _ in ""|ljust:comment.rating %}⭐{% endfor %}
                            </span>
                        </div>

                        <div class="comment-text">{{ comment.text }}</div>

                        <div class="comment-actions">
                            {% if comment.user == request.user and perms.myapp.change_comment %}
                                <a href="{% url 'comment_update' comment.id %}">Редагувати</a>
                            {% endif %}
                            {% if perms.myapp.delete_comment %}
                                {% if comment.user == request.user or is_manager %}
                                    <a href="{% url 'comment_delete' comment.id %}">Видалити</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="empty-message">Ви ще не залишили жодного відгуку.</p>
        {% endif %}

        <div class="comment-actions-bottom footer-class">
            <a class="universal-btn back-btn" href="javascript:history.back()">Назад</a>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/user/user_favorites.html
{% extends 'myapp/template.html' %}
{% load static %}

{% block title %}Список бажань{% endblock %}

{% block content %}
    <div class="page-container">
        <h1 class="main-heading">
            Список бажань
            {% if profile_user.first_name %}
                {{ profile_user.first_name }} {{ profile_user.last_name }}
            {% endif %}
        </h1>


        <div class="products-grid">
            {% for product in favorite_product %}
            <div class="product-card" style="margin-bottom: 25px">
                <a href="{% url 'product_detail' product.id %}">
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image">
                </a>
                <div class="product-info">
                    <h2 class="product-name"><a href="{% url 'product_detail' product.id %}">{{ product.name }}</a></h2>
                    <div class="product-description">{{ product.description }}</div>
                </div>
                <div class="product-actions">
                    <form method="post" action="{% url 'favorite_product' product.pk %}">
                    {% csrf_token %}
                        <button type="submit" class="add-to-wishlist-btn">
                            <i class="fas fa-heart"></i>
                        </button>
                    </form>
                </div>
            </div>
            {% empty %}
                <p class="empty-message">Немає жодного товару у списку бажань.</p>
            {% endfor %}
        </div>
    </div>

    <div class="comment-actions-bottom footer-class">
        <a class="universal-btn back-btn" href="javascript:history.back()">Назад</a>
    </div>
{% endblock %}